# Generated by Django 4.2.10 on 2024-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_post_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
